- name: Install pip
  apt:
    name: python-pip
    state: present

- name: Install "python-apt" package
  apt:
    name: python-apt
    state: present

- name: Install "python-pexpect" package
  apt:
    name: python-pexpect
    state: present
